### ISSUE TITLE
Opening formatting settings crashes VS2017

### ISSUE THREAD

**Issue by dbarnhart** [tgjones/HlslTools#106]
Upon initial installation, the tool works perfectly fine. But after some time, it begins to fail with increasing severity and frequency. At first, certain files will trigger the crash. It's notable that C# intellisense becomes active, yielding C# errors (red underline) in my HLSL files. Adjusting formatting rules still works at this point, but behaves erratically (e.g. if N changes are made to new-line rules, only 1 is saved). Soon, any non-trivial HLSL document will lead to crashes. Even inspecting the formatting settings for the HLSL tool will lead to a crash, but the other settings work.

**Comment by dbarnhart** [comment]
I ran VS2017 with logging, but didn't see anything interesting in the activity log.

**Comment by dbarnhart** [comment]
Ah got this from the debugger:

System.AggregateException occurred
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at ShaderTools.Editor.VisualStudio.Hlsl.Util.Extensions.Extensions.TryGetSemanticModel(ITextSnapshot snapshot, CancellationToken cancellationToken, SemanticModel& semanticModel)
   at ShaderTools.Editor.VisualStudio.Hlsl.IntelliSense.QuickInfo.QuickInfoManager.<>c__DisplayClass6_0.<TriggerQuickInfo>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShaderTools.Editor.VisualStudio.Hlsl.IntelliSense.QuickInfo.QuickInfoManager.<TriggerQuickInfo>d__6.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

Inner Exception 1:
AggregateException: One or more errors occurred.

Inner Exception 2:
NotSupportedException: Not supported: ContinueStatement

**Comment by dbarnhart** [comment]
Duplicate of https://github.com/tgjones/HlslTools/issues/101

**Comment by tgjones** [comment]
Thanks for reporting this - closing as a dupe of #101.
