### ISSUE TITLE
The "FindInstalledExtension" task failed unexpectedly

### ISSUE THREAD

**Issue by jianyunli** [tgjones/HlslTools#109]
I have Visual Studio 2017 Community, cloned the source code and start to debug, got the error below

Severity	Code	Description	Project	File	Line	Suppression State
Error		The "FindInstalledExtension" task failed unexpectedly.
System.Runtime.InteropServices.COMException (0x800700B7): ExternalSettingsManager::GetScopePaths failed to initialize PkgDefManager for C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\devenv.exe
   at Microsoft.VisualStudio.Settings.ExternalSettingsManager.GetScopePaths(String applicationPath, String suffixOrName, String vsVersion, Boolean isLogged, Boolean isForIsolatedApplication)
   at Microsoft.VisualStudio.Settings.ExternalSettingsManager.CreateForApplication(String applicationPath, String rootSuffix)
   at Microsoft.VsSDK.Build.Tasks.ExtensionManagerUtilities.GetSettingsManagerForDevenv(String rootSuffix)
   at Microsoft.VsSDK.Build.Tasks.FindInstalledExtension.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	ShaderTools.Editor.VisualStudio

**Comment by tgjones** [comment]
Do you have the Extension SDK installed? This sounds possibly related. I'm not able to help debug local development issues at the moment, but feel free to re-open if you've installed the Extension SDK and still can't run it.

**Comment by MarkusMiller** [comment]
Hey there

I experienced pretty much the same error. I found this closed issue and double-checked if the extension sdk is installed. Turns out it is installed but I'm still receiving this error. Anything else I might be missing?

Thanks and kind regards
