### ISSUE TITLE
Could not load file or assembly 'System.IO.FileSystem'

### ISSUE THREAD

**Issue by OndrejPetrzilka** [tgjones/HlslTools#86]
I've tried new version with some UI freeze fixes and it crashes right away when opening file
Version: HLSL Tools for Visual Studio v1.1.210
VS2015 Community

Am I missing some dependency (.NET Framework update) or something?
```
System.IO.FileNotFoundException occurred
  HResult=0x80070002
  Message=Could not load file or assembly 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at ShaderTools.Core.Options.ConfigFileLoader.GetConfigFiles(String initialDirectory)
   at ShaderTools.Core.Options.ConfigFileLoader.LoadAndMergeConfigFile(String directory)
   at ShaderTools.Editor.VisualStudio.Hlsl.Util.Extensions.Extensions.<>c__DisplayClass8_0.<GetConfigFile>b__0()
   at Microsoft.VisualStudio.Utilities.PropertyCollection.GetOrCreateSingletonProperty[T](Object key, Func`1 creator)
   at ShaderTools.Editor.VisualStudio.Hlsl.Util.Extensions.Extensions.GetConfigFile(ITextBuffer textBuffer)
   at ShaderTools.Editor.VisualStudio.Hlsl.Util.Extensions.Extensions.<>c__DisplayClass11_0.<GetSyntaxTree>b__0(ITextSnapshot key)
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.GetValue(TKey key, CreateValueCallback createValueCallback)
   at ShaderTools.Editor.VisualStudio.Hlsl.Util.Extensions.Extensions.GetSyntaxTree(ITextSnapshot snapshot, CancellationToken cancellationToken)
   at ShaderTools.Editor.VisualStudio.Hlsl.Navigation.EditorNavigationSource.<>c__DisplayClass5_0.<InvalidateTargets>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShaderTools.Editor.VisualStudio.Hlsl.Navigation.EditorNavigationSource.<InvalidateTargets>d__5.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShaderTools.Editor.VisualStudio.Hlsl.Navigation.EditorNavigationSource.<<Initialize>b__4_0>d.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShaderTools.Editor.VisualStudio.Hlsl.Navigation.EditorNavigationSource.<Initialize>d__4.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

```

**Comment by tgjones** [comment]
@OndrejPetrzilka please could you give the latest version - v1.1.226 or above - a try?

**Comment by tgjones** [comment]
Ignore that - I'm still getting the same error in VS2015. I'll keep working on it.

**Comment by tgjones** [comment]
@OndrejPetrzilka okay, please try v1.1.228, and let me know how you get on.

**Comment by OndrejPetrzilka** [comment]
Works fine

**Comment by tgjones** [comment]
How about the UI freezing issue - is that improved / eliminated in this version?
